language: php
php:
  - '7.1'
  - '7.2'
env:
  global:
    - TEST_COMMAND="composer test"
matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TEST_COMMAND="composer lint"

install:
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install
sudo: true
services:
  - docker
before_script:
  - phpenv config-rm xdebug.ini
script:
  - $TEST_COMMAND
after_success:
  - '[[ !-f tests/_output/coverage.xml ]] || wget https://scrutinizer-ci.com/ocular.phar'
  - '[[ !-f tests/_output/coverage.xml ]] || php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml'
