language: php
php:
  - '7.1'
  - '7.2'
install:
  - travis_retry composer install

script:
  - composer test
sudo: required
services:
  - docker
after_success:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi